version: '3.8'
services:
  registry_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-registry-service
    restart: always
    ports:
      - 8761:8761
    networks:
      network_bank:
        aliases:
          - net_cloud
networks:
  network_bank:
    name: net_cloud
    external: true